### ISSUE TITLE
Not able to load any Flandmark model

### ISSUE THREAD

**Issue by cat3333** [uricamic/clandmark#23]
Hi,  I followed the installation guide and I finished the installation. 
However, I cannot load any flandmark model when I try the static_input example.

Here is the error:
<img width="726" alt="screen shot 2015-10-27 at 8 35 18 am" src="https://cloud.githubusercontent.com/assets/15334075/10746559/2756a06a-7c87-11e5-9829-731be71ab494.png">

and 
<img width="723" alt="screen shot 2015-10-27 at 8 34 40 am" src="https://cloud.githubusercontent.com/assets/15334075/10746564/343ba500-7c87-11e5-9360-cdd820c2c601.png">

I am using cmake version 3.0.2 and opencv version 3.0.0.

Thanks a lot.

**Comment by uricamic** [comment]
Hi @cat3333, 

from the screenshots it seems that Flandmark model was loaded successfully (in both cases). The error message actually comes from the OpenCV haarcascade loading. 
The problem should be solved by adding "/" at the end of the cascade path, since it is not included automatically in the code and when missing it produces wrong path to the cascade. 

I should also mention that the code is intended to be used with models generated by the speedup version of the feature computation, i.e. `flandmark_model.xml` is not compatible with this code - it will result in bad localization of landmarks. 

Also please note that the code is written for OpenCV version 2.x and there are some constant incompatible with OpenCV 3.x.

**Comment by cat3333** [comment]
Thank you very much!! I can successfully run the program by adding "/" at the end of the cascade path. =)

**Comment by uricamic** [comment]
Hi @cat3333, 

I am happy to hear that :)
