### ISSUE TITLE
Can we recognise half face without 1 eye?

### ISSUE THREAD

**Issue by cat3333** [uricamic/clandmark#30]
Hi, thanks for this great jog and answering my last question.

I have run the 'static_input' example with the INDIVIDUAL_FRONTAL_AFLW_SPLIT_1.xml model, and find that the model can detect the faces with 2 eyes but not with only 1 eye. the results are as below.

successful result:
![success](https://cloud.githubusercontent.com/assets/15334075/11019623/b96d66f6-863b-11e5-813d-21d2bccc7b33.png)

failed result:
![fail1](https://cloud.githubusercontent.com/assets/15334075/11019624/bb6ed8e0-863b-11e5-9141-093b2b8f1022.png)
![fail2](https://cloud.githubusercontent.com/assets/15334075/11019625/be29d65c-863b-11e5-87ef-3a710a2c20ce.png)

I would like to know that 
1. can we detect the face with 1 eye using code snippet (http://cmp.felk.cvut.cz/~uricamic/clandmark/#snippets-mv) you provided?
1. If yes, what model we should use in "modelDir" in the main function in the code snippet?

<img width="629" alt="screen shot 2015-11-08 at 5 14 18 pm" src="https://cloud.githubusercontent.com/assets/15334075/11019637/342d7372-863c-11e5-96bb-626af71d476c.png">

**Comment by cat3333** [comment]
The photos I used are from
http://xdesktopwallpapers.com/wp-content/uploads/2012/04/Zooey%20Deschanel%20Sad%20Side%20Face%20Closeup.jpg
http://74211.com/wallpaper/picture_big/Anne-Hathaway-HD-Post-in-Pixel-of-1920x1440-in-Smiling-Facial-Expression-and-Messy-Hair-She-is-Impressive-and-Fit-TV-Movies-Post.jpg
and
http://mag-cosmo-prod-s3.s3.amazonaws.com/legacy/images/beauty/neck.jpg

**Comment by uricamic** [comment]
Hi @cat3333, 

I think the main problem is that those faces have too big inplane rotation (roll angle), which makes them difficult to be detected by a conventional face detector such as OpenCV `haarcascade` used in the examples. 

`CLandmark` expects detected face box on its input, so you can use any technique you want to improve the results. Here are the examples using a [commercial face detector](http://www.eyedea.cz/) (implementing this [paper](https://dspace.cvut.cz/bitstream/handle/10467/9494/2005-Waldboost-learning-for-time-constrained-sequential-detection.pdf?sequence=1)), which is able to detect faces in a full yaw range and inplane rotation up to 90 degrees: 

![anne_det](https://cloud.githubusercontent.com/assets/1597574/11029893/64b155f2-86ca-11e5-8adc-ad3144c3d2fd.jpg)
![neck_det](https://cloud.githubusercontent.com/assets/1597574/11029894/694b2c50-86ca-11e5-8d73-382b54760284.jpg)
![zooey_det](https://cloud.githubusercontent.com/assets/1597574/11029897/6cb6d858-86ca-11e5-991e-154e539bc430.jpg)

So, to answer your questions:
- It is indeed possible to detect close to profile faces (even with a strong inplane rotation), you can use `haarcascade` for profile faces (and try to rotate the image in order to deal with the inplane rotations).
- The `modelDir` in the  code snippet should contain the folder with multi-view model files (`xml` files), which are listed in the `modelList` array.

**Comment by cat3333** [comment]
Thank you very much for the detailed solution!!!
