### ISSUE TITLE
cannot openfile CDPM.xml

### ISSUE THREAD

**Issue by travischan** [uricamic/clandmark#79]
@uricamic I was trying the examples, but having trouble here. Hoping for your help, thanks!
![qq 20170317145822](https://cloud.githubusercontent.com/assets/13619803/24032357/87e72cbc-0b22-11e7-9828-d99d7650b834.png)
![qq 20170317150412](https://cloud.githubusercontent.com/assets/13619803/24032453/0ba1f348-0b23-11e7-8017-cf39832c8510.png)
![qq 20170317150833](https://cloud.githubusercontent.com/assets/13619803/24032561/a729717e-0b23-11e7-84d4-3d9caf7eb8cb.png)

**Comment by uricamic** [comment]
Hi @TravisChan, 

from the screenshots, I guess the problem is the space ` ` between the path to the folder containing the `.xml` models and the `CDPM.xml`. The examples expect the path to the model including the model name. 
Try something like this:
``static_input C:\Users\chan\Desktop\C2F-DPM_models\CDPM.xml face.jpg faceout.jpg``

**Comment by travischan** [comment]
Hi, @uricamic Thanks for your response. 
But it still can't work as the screenshot shows. 
![_20170318235317](https://cloud.githubusercontent.com/assets/13619803/24073687/6370100a-0c36-11e7-96e8-5aa88e887aff.png)

**Comment by uricamic** [comment]
Hi @TravisChan, 

sorry, I didn't notice you are not passing the path to `haarcascade_frontalface_alt.xml` as well. So, if you have this file in the same directory as the static_input executable, you should use:

``static_input .\ C:\Users\chan\Desktop\C2F-DPM_models\CDPM.xml face.jpg faceout.jpg``

as the [static_input.cpp](https://github.com/uricamic/clandmark/blob/master/examples/static_input.cpp#L120) suggests. There is a wrong usage message output in case when the instance of the CLandmark class is not created successfully, which I have to fix.

**Comment by travischan** [comment]
Hi @uricamic 
It still has a little problem like this. 
![_20170319000959](https://cloud.githubusercontent.com/assets/13619803/24073814/a641d8c6-0c38-11e7-9f20-1d68664a8953.png)

**Comment by uricamic** [comment]
@TravisChan 

this error shows only if you do not have the `haarcascade_frontalface_alt.xml` in the path provided as the first argument. In your case the current working directory. 
Just copy this file there or provide a path to a directory containing this file and it should work.

**Comment by travischan** [comment]
@uricamic 
It works, thanks a lot! You have been a great help.

**Comment by uricamic** [comment]
@TravisChan 
No problem

**Comment by MosyMosy** [comment]
Hi, I get "Flandmark model loaded in 196.26 ms --(!)Error loading" while i think every thing is true.
this is my files:
![1](https://user-images.githubusercontent.com/40351294/41522443-c850141e-728a-11e8-8f4d-df60e9d949c3.png)
And this is my cmd:
![1](https://user-images.githubusercontent.com/40351294/41522489-022ad232-728b-11e8-8c70-573edf3f86ea.png)
 I don't know why i'm getting this error

**Comment by uricamic** [comment]
Hi @MosyMosy, 

the problem is not in loading the flandmark model, but in loading the haarcascade. If you look in the static_input.cpp file, you will see that it expects just the path to the folder which contains `haarcascade_frontalface_alt.xml` [(here)](https://github.com/uricamic/clandmark/blob/master/examples/static_input.cpp#L155). 

So, all you need to do is to change the call to something like this: 
`static_input .\ CDPM.xml face.jpg faceout.jpg`

Sorry for the confusion.
